services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy_manager
    restart: unless-stopped
    ports:
      # These are the Public Ports
      - '80:80'   # HTTP
      - '443:443' # HTTPS
      - '81:81'   # Admin Web UI
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
