services:
  clickhouse:
    image: clickhouse/clickhouse-server
    restart: always
    container_name: sandbox-clickhouse
    ports:
      - "7041:8123" # Web Interface
      - "7040:9000" # TCP
    networks:
      - network_db
    volumes:
      - ./ch_data:/var/lib/clickhouse
      - ./ch_logs:/var/log/clickhouse-server
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=root
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
networks:
  network_db:
    external: true
